version: '0.1'

services:
  rpa-mit-reference-data:
    build:
      target: development
    environment:
      - DbConnectionString=${POSTGRES_CONNECTION}
    ports:
      - "3000:3000"
    volumes:
      - ./RPA.MIT.ReferenceData:/home/dotnet/RPA.MIT.ReferenceData
      - ./RPA.MIT.ReferenceData.Tests:/home/dotnet/RPA.MIT.ReferenceData.Tests

  rpa-mit-reference-data-postgres:
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: