version: '0.1'

services:
  rpa-mit-reference-data:
    build:
      context: .
      args:
        - Package_Feed=${RPA_PACKAGE_FEED}
        - Nuget_Username=${NUGET_USERNAME:-PAT}
        - Nuget_PAT=${NUGET_PAT}
      target: production
    image: rpa-mit-reference-data
    container_name: rpa-mit-reference-data
    depends_on:
      - rpa-mit-reference-data-postgres
    environment:
      - DbConnectionString=${POSTGRES_CONNECTION}

  rpa-mit-reference-data-postgres:
    image: postgres:15.3-alpine
    environment:
      POSTGRES_DB: rpa_mit_reference_data
      POSTGRES_USERNAME: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASS:-password}